skip_commits:
  files:
    - README.md

image: Visual Studio 2017

before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore

build_script:
  - cmd: dotnet publish
  
after_build:
  - 7z a AspnetCore.zip %APPVEYOR_BUILD_FOLDER%\src\bin\Debug\netcoreapp2.0\publish\*.*
  
artifacts:
 - path: AspnetCore.zip
   name: AspnetCore
   type: zip
